### PR TITLE
Show the River of CPAN position for distributions

### PR DESCRIPTION
**Pull request by tsibley**
Affects the search results, the release page and all documentation pages
under a release, and all tables of releases (recent page, author page,
reverse dependencies, etc).

Resolves GH#1679.

### CODE REVIEW

**Comment by oalders** [comment]
Restarted the build as it's not obvious to me how the test failure would be related to this code.

**Comment by tsibley** [comment]
Ah, the failure probably is real. I bet the test is too coupled to the author release table.  I’ll take a look this week.

**Comment by tsibley** [comment]
Repushed with a small correction to the `t/controller/author.t` file that makes it pass locally.

**Comment by oalders** [comment]
Thanks @tsibley!

**Pull request merged**
