### PR TITLE
Switch from AnyEvent to IO::Async

### PR DESCRIPTION
**Pull request by haarg**
We use AnyEvent to run multiple HTTP requests simultaneously.  This converts those to using Net::Async::HTTP.  All of the API model methods have been changed to consistently return futures that can be fetched with `->get`, which should make it easier to clean up how we are using concurrent requests.

Additionally includes a rewrite of the site map generation to something that should actually work, and some other prereq cleanups.

### CODE REVIEW

**Comment by haarg** [comment]
I pulled some changes from this PR out into #1915 because they are simpler and don't rely on this.  Will rebase this once that PR is merged.

**Comment by mickeyn** [comment]
@haarg merged

**Comment by haarg** [comment]
The sitemap changes could maybe go in a separate PR, but to handle it sensibly it would have to depend on this one, and require an additional cpanfile.snapshot regeneration.  The existing sitemap code doesn't even work properly, and we aren't running it on the servers.

**Comment by mickeyn** [comment]
it's OK with me (i'm known to combine several issues in single PRs :))

**Pull request merged**
