### PR TITLE
update Fastmail sponsorship for new branding

### PR DESCRIPTION
**Pull request by rjbs**
Hey, friends!  We lowercased our M and made our logo more circular.  Pretty great, right?

💙

### CODE REVIEW

**Comment by atoomic** [comment]
@rjbs this should be live at https://metacpan.org/about/sponsors

**Comment by rjbs** [comment]
Not seeing it yet, but maybe it's aggressively cached in the CDN.  I'll check again in a bit, unless you're sure it should be there already.

**Comment by oalders** [comment]
```
$ curl -XPURGE https://metacpan.org/static/images/sponsors/fastmail.png
{"status": "ok", "id": "17354-1577180731-63546000"}
```

I can see the new logo now.

**Comment by rjbs** [comment]
Thanks!  The logo looks very weird.  I will go talk to my image-making person about this, though.

**Pull request merged**
