### PR TITLE
add rt.cpan sunset notice

### PR DESCRIPTION
**Pull request by MartinMcGrath**
No end date specified in the comments due to the current situation. Worth putting front and centre as this has not been well communicated as far as I can tell.

References:

https://perl.topicbox.com/groups/infrastructure/Te92859202f730470

https://www.nntp.perl.org/group/perl.perl5.porters/2021/01/msg258825.html

### CODE REVIEW

**Comment by oalders** [comment]
Thanks @MartinMcGrath! Could you attach a screen shot of your browser with this change?

**Comment by MartinMcGrath** [comment]
@oalders excuse the delay, as requested.

Screenshot_2021-01-20_20-47-53

**Comment by oalders** [comment]
Thanks @MartinMcGrath!

**Comment by oalders** [comment]
Screen Shot 2021-01-21 at 10 28 39 AM

**Comment by oalders** [comment]
It would be nice to preserve the alignment of the original screen shot once the width increases.

**Comment by MartinMcGrath** [comment]
Sorry, I'll fix that this evening after work, when I've access a larger
screen.

**Comment by djzort** [comment]
It may be worth rephrasing the notice to use less jargon. 

**Notice: The rt.cpan.org bugtracker is closing down soon!**

**Comment by oalders** [comment]
Right, that may be helpful to folks who don't speak English (or Latin?) as a first language. We would accept a PR for that.

**Pull request merged**
