### PR TITLE
add missing abstracts in Release page

### LINKED ISSUE #1743: (v1) Abstracts not displayed on release pages
For example, compare https://v1.metacpan.org/release/JV/App-Music-ChordPro-0.63 to https://metacpan.org/release/JV/App-Music-ChordPro-0.63

### PR DESCRIPTION
**Pull request by mickeyn**
fixes #1743

### CODE REVIEW

**Comment by haarg** [comment]
Is there a reason we want to pick out individual fields rather than just everything that is in _source?

**Comment by mickeyn** [comment]
TBH, I think you're right. I followed the example of the existing modules there.
The `_source` is a change from ES0.x to ES2.x where we have to pull `_source` separately and not through `fields` - so with the given query, it should be there.
I'll fix that.

**Comment by mickeyn** [comment]
simplified :)
thanks @haarg

**Comment by oalders** [comment]
Thanks!

**Pull request merged**
