### PR TITLE
Highlight modules/dists that have a special co-maintainer (ADOPTME, HANDOFF or NEEDHELP) - Closes #1643 - Attempt 2

### LINKED ISSUE #1643: highlight modules or dists with ADOPTME or HANDOFF or NEEDHELP
It is intolerably hard to declare that you don't want to deal with a CPAN module anymore.  No matter what, it just sits there under your name, inviting bug reports, no matter how many times you say "No, I'm done."  (It's even worse if you're only co-maint, but that's another matter.)

One accepted but basically unsupported solution is to [use special permissions users](http://neilb.org/2013/08/07/adoptme.html) to indicate the idea that you want to transfer permissions away, or just get more hands at work.  Unfortunately, _nobody benefits from this_, because _nobody can tell_ they've been assigned unless they go look in 06perms, which is far, far more than anyone should be expected to do.

It would be useful if the MetaCPAN web site would throw up a big notice like:
- ADOPTME: This distribution is up for adoption!  Contact the modules list if you want to take over.
- HANDOFF: This distribution's maintainer is looking for someone to take over!  Contact them…

### PR DESCRIPTION
**Pull request by ThisUsedToBeAnEmail**
Highlight modules or dists with ADOPTME or HANDOFF or NEEDHELP.

A notification will display at the top of the page in /release and /pod if ADOPTME, HANDOFF or NEEDHELP is found as an author within the modules permissions.

### CODE REVIEW

**Comment by haarg** [comment]
Can you adjust the commit subjects to be more descriptive?  References to issue numbers aren't particularly helpful when scanning through a git log.

I'll try to provide some additional feedback over the next day or so.  If I don't get around to that though, this looks OK to merge.

**Comment by oalders** [comment]
@ThisUsedToBeAnEmail I think what @haarg was referring to was the subject line of 3fb9833c111b2419c8a.  If that comes up in the git logs it won't be that helpful without digging in to the actual commit message.

**Comment by oalders** [comment]
You could just remove `Closes ISSUE-1643 - Attempt 2` and the next line could be the commit subject.

**Comment by ThisUsedToBeAnEmail** [comment]
I will take a look tomorrow but we all have a different workflow - Is there any documentation on the practices for this project.

My workflow for $work is - 

Subject - Closes #PROJECT-{ID} - which usually links to a JIRA ticket.

Body - description of what has changed

**Comment by ThisUsedToBeAnEmail** [comment]
Updated

**Comment by oalders** [comment]
> Is there any documentation on the practices for this project.

No, which is unfortunate.  It's mostly kind of standard stuff for open source Perl work and whatever comes up in code review or gets flagged by `perltidy`.

**Pull request merged**
