### PR TITLE
Remove some unneeded prereqs

### PR DESCRIPTION
**Pull request by haarg**

### CODE REVIEW

**Comment by oalders** [comment]
Looks like `Regexp::Common` is still needed somewhere.

**Comment by haarg** [comment]
Fixed.

Also had to poke the build due to https://rt.cpan.org/Ticket/Display.html?id=135347 causing a failure.

**Review by oalders — APPROVED** [review]
Nice cleanups! 🧹

**Comment by oalders** [comment]
> Also had to poke the build due to https://rt.cpan.org/Ticket/Display.html?id=135347 causing a failure.

Hat tip to @manwar for maintaining this!

**Pull request merged**
