### PR TITLE
only use gravatars based on user emails

### LINKED ISSUE #1022: Can't use gravatar after having a custom avatar URL
Quoting @benkasminbullock on #606:

> there seems to be a bug here that if the avatar is entered and then removed again, the gravatar avatar doesn't come back. Shouldn't it use a checkbox for gravatar and label the input box as an alternative to gravatar?

I had a custom avatar URL, but when I try to remove it, I get no avatar at all, instead of using gravatar. There appears to be no way at all for me to make my account use gravatar (other than manually specifying the right gravatar URL, which is what I currently do).

### PR DESCRIPTION
**Pull request by haarg**
This removes the use of avatars customizable through the account page.
Instead, gravatars based on the users emails is used, falling back to
identicons.

The customizable avatars did not work well for the multiple sizes we
wanted to display them in.  This was also a problem for our fallback
icon.  The user images would often be served through http, not https,
giving mixed mode alerts.  If the user modified their profile, the
generated gravatar URL would be baked in, preventing updates to their
email address from updating the avatar.

Fixes #1022, #1623, #2055.

### CODE REVIEW

**Comment by karenetheridge** [comment]
nice - this means that Gravatar::URL is now going to be consistent with what metacpan displays.

**Comment by Grinnz** [comment]
Not sure how you're testing it, but Gravatar::URL for that user's email address gives me http://www.gravatar.com/avatar/629e016f4d4cf66337b150a0287a2236.

**Comment by karenetheridge** [comment]
I was in error when I mentioned Gravatar::URL -- actually the problem (this is in Acme::CPANAuthors::Nonhuman FWIW - my most important distribution ever /s) is that the data returned by https://fastapi.metacpan.org/v1/author/$author still contains the custom avatar URLs, not those fetched via Gravatar::URL.  e.g. https://fastapi.metacpan.org/v1/author/ZDM still contains the custom icon rather than default pixel art.

**Comment by karenetheridge** [comment]
To be more specific: there is an unfinished part of the change covered by this pull request -- the API needs to be updated to be consistent with the new value used by the front end.

**Comment by haarg** [comment]
I'm more inclined to remove the value from the API.

**Pull request merged**
