### PR TITLE
add LPW information to banner

### PR DESCRIPTION
**Pull request by leejo**
PTS is now over and LPW is looking for attendees and sponsors after a five year break. w/r/t d34b6a969db7cf2edf7945b9561959352eab1ad1

### CODE REVIEW

**Comment by oalders** [comment]
@dhogan8 I was thinking maybe we could use a different bg colour here to distinguish this banner from the previous one. Any thoughts on that?

**Comment by dhogan8** [comment]
@oalders I haven't spun up the dev environment for this branch yet, but is this replacing the `The Perl Toolchain Summit needs more sponsors....` banner or going underneath it?

**Comment by oalders** [comment]
@dhogan8 this will be replacing it. That banner was removed in a previous commit, but it hasn't been deployed yet. My concern is that if it looks a lot like the previous banner, people won't pay attention to it.

**Comment by dhogan8** [comment]
How about `#006081`?
Screenshot 2024-05-03 at 9 54 00 AM

**Comment by leejo** [comment]
I've amended the commit to tweak the background colour to `#006081` 👍

**Review by dhogan8 — APPROVED** [review]

**Comment by leejo** [comment]
Rebased my branch against upstream `master`

**Review by dhogan8 — APPROVED** [review]

**Comment by leejo** [comment]
Looks like there's some issue in the CI related to code coverage uploads?

**Pull request merged**
