### PR TITLE
use dropdown for module/author search selection

### PR DESCRIPTION
**Pull request by danmcc**
This addresses issue #1554, at least on the homepage.  Take a peek and let me know what ya think.  If it looks good, I can put it on search result pages, too.  Feel free to edit the implementation as you see fit.  I'm not the world's best front-end developer, so am happy to have someone else improve on it.

### CODE REVIEW

**Comment by oalders** [comment]
@danmcc, thanks for this!  Sorry for my delay in reviewing.

I think it's just the tidy test that is failing here.  That's easy for us to fix.  I've included a screen shot of the changes.  I think we may want to add some kind of colour to the dropdown.

screenshot 2015-08-19 09 39 35

Anyone have thoughts on the UI?

**Comment by oalders** [comment]
@rwstauner, @haarg, @ranguard feedback?

**Comment by rwstauner** [comment]
One problem i see is that the cursor changes on the wrapper, but the dropdown trigger is smaller, so the first few times i clicked, nothing happened.
screenshot - 08222015 - 10 08 24 am

**Comment by rwstauner** [comment]
Another is that we lost some valuable attributes on the searchbox like `name="q"` and `autofocus`.

**Comment by rwstauner** [comment]
Since this is only for autocomplete (it doesn't affect the search results)
i wonder if we should say "Autocomplete" somewhere (it would have fit before the radios, it could fit in the new button, or maybe just title attribute (hover text))...

**Comment by kentfredric** [comment]
I guess some of the confusion in #1554 for me really, is due to the fact I can't think of another time I wanted a choice for an autocomplete

Autocomplete is supposed to be inherently a simple things that give a best first-pass without needing to think, and even providing a choice mechanism there just adds to confusion.

I'd be ok with the selection changing how the *main* search works, but it just doesn't, and that it doesn't is part of the confusion.

Instead of proving a choice of which completion to use, seeing we only have two, why can't we have the results of both in the same? 

snapshot5

Or maybe something inline that assumes you're already done typing and then switches the result drop down?

snapshot6

**Comment by danmcc** [comment]
Sorry for the delay on this.  I finally got time to sit down and play with it a bit and create a mockup.  If we combine the two datasets, we could serve a single autocomplete as shown below.  (This would require moving the module autocomplete to Constructor.io, but I think that would offer a huge improvement in the results that are shown.)

What do you all think?

image

**Comment by oalders** [comment]
Visually, that works for me.  My main concern would be around keeping the data up to date on your end.  What would your plan be for that?  Can we push to you or do you need to pull?

**Comment by danmcc** [comment]
Yup, you can push to us.  We'd work together to integrate our [API](constructor.io/docs).  I can start poking around with it if you point me to where in the code it'd make sense to push to us.

**Comment by oalders** [comment]
So, I think I'd like us to come back to this _after_ the QA hackathon, which is in about 3 weeks.  Once we've moved to Elasticsearch 2.0 we'll have a better idea of how our module search is broken (or fixed?)

However, it looks like we could use https://metacpan.org/pod/WebService::ConstructorIO to come up with the integrated author and module search suggestions.

@danmcc could you set us up with the account credentials to do this?  You can email me directly.  I'd be interested to see how easy this is.

**Comment by danmcc** [comment]
Will do @oalders!  Our Perl API docs are [here](https://constructor.io/docs/?perl) if you'd like to take a gander.

**Comment by mickeyn** [comment]
is this PR still relevant?

**Comment by oalders** [comment]
I think with @haarg adding the author search to the dropdown it's no longer needed.  It's my fault for not getting to this.  I had the best of intentions, but at the end of the day, I just didn't get to it.  My apologies to @danmcc :(

**Pull request closed without merging**
